### PR TITLE
Make get, set, load, save public methods

### PR DESCRIPTION
**Pull request by imagejan**
This will make TJ_Matrix useful for storing and retrieving matrices from scripts. I needed this for a script and thought it would be generally useful to make these methods public.

### CODE REVIEW

**Comment by ctrueden** [comment]
@emeijering What do you think?

**Comment by emeijering** [comment]
@ctrueden @imagejan The proposed change is fine with me. I already merged it.

**Comment by imagejan** [comment]
Thanks!
@ctrueden I think pom.xml has to be updated for this to be picked up by jenkins. Is that correct? I wasn't sure, otherwise I had included the version increase into the PR..

**Comment by emeijering** [comment]
@ctrueden Feel free to update the pom.xml as needed, including the version number mentioned in that file (for example increase to 2.8.4). But I prefer to keep the official version number as is (see my previous comment concerning this issue).

**Comment by hinerm** [comment]
@imagejan Jenkins is configured to automatically build and deploy Maven artifacts when there are any changes to `master`. Looks like this [built successfully](http://jenkins.imagej.net/job/TransformJ/) on the 21rst.
For it to be uploaded to Fiji, we would cut a new release (2.9.0 since it adds public API) and update [pom-fiji](https://github.com/fiji/pom-fiji/blob/pom-fiji-8.0.0/pom.xml#L219)

**Pull request merged**
